backend:
  name: github
  # GANTI INI: Formatnya username-github-kamu/nama-repository
  # Contoh jika username kamu jagoanweb: jagoanweb/smpn1damai-main
  repo: perpussemangatpagi/smpn1damai
  branch: main # Pastikan nama branch utamamu benar "main" (atau "master")

# Pengaturan folder penyimpanan gambar yang di-upload
media_folder: "images"
public_folder: "/images"

# Struktur Form untuk Humas
collections:
  - name: "berita"
    label: "Berita Sekolah"
    folder: "content/berita" # Hasil ketikan Humas akan masuk ke folder ini
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Judul Berita", name: "title", widget: "string" }
      - { label: "Tanggal Publikasi", name: "date", widget: "datetime" }
      - { label: "Foto Dokumentasi", name: "thumbnail", widget: "image", required: false }
      - { label: "Penulis", name: "author", widget: "string", default: "Admin Web SMPN 1 Damai" }
      - { label: "Isi Berita", name: "body", widget: "markdown" }
